### ISSUE TITLE
How to install these missing nodes? 

### ISSUE THREAD

**Issue by shiverwang76** [kijai/ComfyUI-MochiWrapper#18]
Hello, I am a beginner, how to install these missing nodes? 
Thanks you!

DownloadAndLoadMochiModel
MochiTextEncode
MochiSampler
MochiDecode

**Comment by perk11** [comment]
Go to `custom_nodes` directory in ComfyUI
```
git clone git@github.com:kijai/ComfyUI-MochiWrapper.git
cd ComfyUI-MochiWrapper
pip install -r requirements.txt
pip install SageAttention 
```

**Comment by shiverwang76** [comment]
> 转到 ComfyUI 中的目录`custom_nodes`
> 
> ```
> git clone https://github.com/kijai/ComfyUI-MochiWrapper.git
> cd ComfyUI-MochiWrapper
> pip install -r requirements.txt
> pip install SageAttention 
> ```

The problem has been solved, thank you very much!

**Comment by yovsac** [comment]
Hello, have done this but still cant see the nodes, still red. Any other ideas?

**Comment by kijai** [comment]
> Hello, have done this but still cant see the nodes, still red. Any other ideas?

Update torch to 2.5.0

**Comment by shiverwang76** [comment]
> Hello, have done this but still cant see the nodes, still red. Any other ideas?

In my experience, many comfyui nodes have conflicts, if upgrading torch still does not solve the problem, please create a new comfyui directory (for mochi only), may solve the problem

**Comment by yovsac** [comment]
Thank you for your reply. Sorry for the silly question, but how do I install torch 2.5?

**Comment by shiverwang76** [comment]
> Thank you for your reply. Sorry for the silly question, but how do I install torch 2.5?

Try any of the following command lines:

pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu118
pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121
pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu124

**Comment by shiverwang76** [comment]
> Thank you. I would use any of those commands on a cmd window in the mochi folder or the comfy one?

Yes, it seems mochi has no strict requirements for the cuda version. In my own case, I use cu118

**Comment by yovsac** [comment]
sorry Im a bit new all this. I get this error. What im I doing wrong?
![Screenshot 2024-10-28 101154](https://github.com/user-attachments/assets/8b20c3e7-c448-49e4-8c7c-b15ac6273375)

**Comment by yovsac** [comment]
> > Thank you. I would use any of those commands on a cmd window in the mochi folder or the comfy one?
> 
> Yes, it seems mochi has no strict requirements for the cuda version. In my own case, I use cu118

![Screenshot 2024-10-28 102112](https://github.com/user-attachments/assets/85750b69-b604-46aa-a8f6-277fa3e6a003)

Get this window when I try to do it in the /python_embeded folder

**Comment by kijai** [comment]
> > > Thank you. I would use any of those commands on a cmd window in the mochi folder or the comfy one?
> > 
> > 
> > Yes, it seems mochi has no strict requirements for the cuda version. In my own case, I use cu118
> 
> ![Screenshot 2024-10-28 102112](https://private-user-images.githubusercontent.com/122029652/380650698-85750b69-b604-46aa-a8f6-277fa3e6a003.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDc4ODcsIm5iZiI6MTczMDEwNzU4NywicGF0aCI6Ii8xMjIwMjk2NTIvMzgwNjUwNjk4LTg1NzUwYjY5LWI2MDQtNDZhYS1hOGY2LTI3N2ZhM2U2YTAwMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwOTI2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjhiMGQ4ODdhNGJiMGQ3OGEwOWQyZWM1MzgwNmI5YzM4NDc1MWFlZjcyN2NmNmVlMWIzMDYzMDlhNjc1YzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nl_lasyRplvAs_8q8-9ELDms_dhxDtgYeksiMbm4tPo)
> 
> Get this window when I try to do it in the /python_embeded folder

Run In the `ComfyUI_windows_portable\python_embeded` folder:
`python.exe -m pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124`

**Comment by yovsac** [comment]
Still getting the same window...frustrating.
![Screenshot 2024-10-28 104006](https://github.com/user-attachments/assets/bb1e70fe-9075-414e-a0e1-bbd124c06cd1)

**Comment by shiverwang76** [comment]
> Still getting the same window...frustrating. ![Screenshot 2024-10-28 104006](https://private-user-images.githubusercontent.com/122029652/380657642-bb1e70fe-9075-414e-a0e1-bbd124c06cd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzA0NTEsIm5iZiI6MTczMDEzMDE1MSwicGF0aCI6Ii8xMjIwMjk2NTIvMzgwNjU3NjQyLWJiMWU3MGZlLTkwNzUtNDE0ZS1hMGUxLWJiZDEyNGMwNmNkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNTQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjI4NjM5NGI0Nzc0MDE3MmI0MDlkNmFmNmIyNTExMGYzYTkzYzc4NzA5ZTE5ZjYyYzQ3MmMzMjZkYjY5NzEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kDknlAmwTj8nmDL0mBocncGDN1wi7rT-Xfl7h8iTE8s)

It feels like there are many possibilities, maybe there is a problem with the version of python you installed? Try to install a version that is compatible with your system. Use the following two lines to see the version?
python --version
python -c "import platform;  print(platform.architecture())"

Or if phthon hasn't been upgraded to a new version, try:
python -m pip install --upgrade pip

**Comment by yovsac** [comment]
Thank you for your reply. I ended up having problems even starting comfy with the same message so I reinstalled comfy and nodes and it’s working now. Thanks again 👍

**Comment by hoyleontour** [comment]
> Go to `custom_nodes` directory in ComfyUI
> 
> ```
> git clone https://github.com/kijai/ComfyUI-MochiWrapper.git
> cd ComfyUI-MochiWrapper
> pip install -r requirements.txt
> pip install SageAttention 
> ```

Top man. Thanks for the advice. Worked a treat.
